server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: rails
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /rails/log/development.log

  - job_name: sidekiq
    static_configs:
      - targets:
          - localhost
        labels:
          __path__: /rails/log/sidekiq.log
